### ISSUE TITLE
Neat library

### ISSUE THREAD

**Issue by ankane** [yoshoku/rumale-torch#1]
Hey @yoshoku, just wanted to say this is really neat. Love how concise the training code is.

**Comment by yoshoku** [comment]
@ankane Thank you for developing the wonderful library torch.rb. I plan to develop Rumale::Torch as a library that can easily describe neural networks such as lasagne, tflearn and skorch.

**Comment by ankane** [comment]
Nice, l like the concept and will follow along. If you find anything missing from Torch.rb that'd be useful, don't hesitate to create an issue.
